### ISSUE TITLE
Android build fails with Expo 48 when this plugin is included

### ISSUE THREAD

**Issue by chrisknepper** [allboatsrise/expo-marketingcloudsdk#15] opened 2023-06-07 23:45 UTC
expo-marketingcloudsdk: 48.0.3
expo: 48.0.0

iOS builds successfully.

Both worked fine with Expo 47.

App builds for both platforms if this plugin and its app.config block are removed.

app.config:

```
[
    "@allboatsrise/expo-marketingcloudsdk",
    {
        appId: process.env.MC_APP_ID,
        accessToken: process.env.MC_ACCESS_TOKEN,
        serverUrl: process.env.MC_APP_SERVER_URL,
    },
],
```

Log of gradlew from EAS build:

```
Running 'gradlew :app:assembleDebug' in /home/expo/workingdir/build/android
Downloading https://services.gradle.org/distributions/gradle-7.5.1-all.zip
10%
20%.
30%.
40%.
50%.
60
%.
70%
80%
90%
100%
Welcome to Gradle 7.5.1!
Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
 - Much more responsive continuous builds
 - Improved diagnostics for dependency resolution
For more details see https://docs.gradle.org/7.5.1/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.5.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
> Task :react-native-gradle-plugin:pluginDescriptors
> Task :react-native-gradle-plugin:processResources
> Task :expo-dev-launcher-gradle-plugin:pluginDescriptors
> Task :expo-dev-launcher-gradle-plugin:processResources
> Task :expo-dev-launcher-gradle-plugin:compileKotlin
> Task :expo-dev-launcher-gradle-plugin:compileJava NO-SOURCE
> Task :expo-dev-launcher-gradle-plugin:classes
> Task :expo-dev-launcher-gradle-plugin:jar
> Task :expo-dev-launcher-gradle-plugin:inspectClassesForKotlinIC
> Task :react-native-gradle-plugin:compileKotlin
> Task :react-native-gradle-plugin:compileJava NO-SOURCE
> Task :react-native-gradle-plugin:classes
> Task :react-native-gradle-plugin:inspectClassesForKotlinIC
> Task :react-native-gradle-plugin:jar
> Configure project :allboatsrise-expo-marketingcloudsdk
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
> Configure project :app
ℹ️  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@2.2.1)
[stderr] 
FAILURE: Build completed with 2 failures.
[stderr] 
1:
[stderr] 
Task failed with an exception.
[stderr] 
-----------
[stderr] 
* Where:
[stderr] 
Build file '/home/expo/workingdir/build/android/app/build.gradle' line: 21
[stderr] 
* What went wrong:
[stderr] 
A problem occurred evaluating project ':app'.
[stderr] 
> path may not be null or empty string. path=''
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
>
[stderr] 
Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
2: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
A problem occurred configuring project ':app'.
[stderr] 
> compileSdkVersion is not specified. Please add it to build.gradle
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
* Get more help at
[stderr] 
https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
10 actionable tasks: 10 executed
[stderr] 
BUILD FAILED in 2m 10s
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

**Comment by andrejpavlovic** [comment] 2023-07-05 16:26
Were you able to figure out the issue? From the stack trace above, it's not clear to me the issue is related to this plugin.

**Comment by andrejpavlovic** [comment] 2023-07-10 18:31
Closing due to lack of input.

**Closed as completed by andrejpavlovic** 2023-07-10 18:31 UTC
